### ISSUE TITLE
glclientで~/.glclient/tmp以下の.lockファイルが削除されないためディレクトリが残る

### ISSUE THREAD

**Issue by tkimuranet** [montsuqi/panda#249]
glclientで~/.glclient/tmp以下にディレクトリが残ったままになる現象が発生しております。
起動時に古いファイルの削除処理が走りますがutils.cのrm_r_old()の中で、"."・".."を除外する処理が先頭の"."で判定しているため.lockファイルも再帰的な削除の対象外となっていて残ってしまうようです。

**Comment by yusukemihara** [comment]
確認しました。ご指摘の通りのようですので修正します。

**Comment by yusukemihara** [comment]
#250 で修正しました。
